AUDIO_SAMPLERATE = 16000

FM_QUAD_RATE = AUDIO_SAMPLERATE * 4
BFM_QUAD_RATE = AUDIO_SAMPLERATE * 16

# RSSI LowPass RC Filter Alpha
RSSI_LOWPASS_TC = 0.125
RSSI_UPDATE_FREQ_HZ = 4
STATUS_UPDATE_TIME_S = (1 / RSSI_UPDATE_FREQ_HZ)

# Noise Floor RC Filter Alpha
NOISEFLOOR_LOWPASS_TC = 60
NOISEFLOOR_LOWPASS_A = (1 / (RSSI_UPDATE_FREQ_HZ * NOISEFLOOR_LOWPASS_TC))

