AUDIO_SAMPLERATE = 16000

# TODO remove these - replace with PREFERRED_SAMPLERATE_FACTOR
FM_QUAD_RATE = AUDIO_SAMPLERATE * 4
BFM_QUAD_RATE = AUDIO_SAMPLERATE * 16

# Set a maximum samplerate to limit processing requirements
MAX_RF_SAMPLERATE = 2_500_000


# RSSI LowPass RC Filter Alpha
RSSI_LOWPASS_TC = 0.125
RSSI_UPDATE_FREQ_HZ = 4
STATUS_UPDATE_TIME_S = (1 / RSSI_UPDATE_FREQ_HZ)

# Noise Floor RC Filter Alpha
NOISEFLOOR_LOWPASS_TC = 60
NOISEFLOOR_LOWPASS_A = (1 / (RSSI_UPDATE_FREQ_HZ * NOISEFLOOR_LOWPASS_TC))

# Volume RC Filter Alpha
VOLUME_LOWPASS_ATTACK_TC = 0.025
VOLUME_LOWPASS_DECAY_TC = 0.25

